import type { Event } from './types'

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt-1',
    title: 'Кавказская война: мифы и факты',
    description:
      'Открытая лекция историка Андрея Волкова о ключевых событиях Кавказской войны 1817–1864 годов. Разберём устойчивые мифы и обратимся к первоисточникам — мемуарам участников и архивным документам эпохи.',
    type: 'lecture',
    location: 'Библиотека им. Ленина',
    address: 'Москва, Воздвиженка 3/5',
    startsAt: new Date('2025-05-15T18:00:00'),
    endsAt:   new Date('2025-05-15T20:00:00'),
    coverUrl: null,
    isFree:   true,
    price:    null,
    currency: 'RUB',
    maxSeats: 60,
    isOnline: false,
    onlineUrl: null,
    createdAt: new Date('2025-04-01'),
  },
  {
    id: 'evt-2',
    title: 'Народы Кавказа: языки и культуры',
    description:
      'Этнографическая встреча с профессором Тбилисского университета Нино Чиковани. Обсудим языковое многообразие региона, традиции гостеприимства и общие корни кавказских культур.',
    type: 'meeting',
    location: 'Центр «Кавказ»',
    address: 'Санкт-Петербург, Невский пр. 88',
    startsAt: new Date('2025-05-22T17:30:00'),
    endsAt:   new Date('2025-05-22T19:30:00'),
    coverUrl: null,
    isFree:   false,
    price:    500,
    currency: 'RUB',
    maxSeats: 40,
    isOnline: false,
    onlineUrl: null,
    createdAt: new Date('2025-04-05'),
  },
  {
    id: 'evt-3',
    title: 'Выставка «Кавказ в объективе XIX века»',
    description:
      'Первые фотографии Кавказа — редкие снимки 1860–1900-х годов из частных коллекций. На выставке представлено более 80 работ, запечатлевших горные аулы, базары Тифлиса и портреты горцев.',
    type: 'exhibition',
    location: 'Музей Востока',
    address: 'Москва, Никитский бульвар 12А',
    startsAt: new Date('2025-06-01T10:00:00'),
    endsAt:   new Date('2025-07-31T19:00:00'),
    coverUrl: null,
    isFree:   false,
    price:    400,
    currency: 'RUB',
    maxSeats: null,
    isOnline: false,
    onlineUrl: null,
    createdAt: new Date('2025-04-10'),
  },
  {
    id: 'evt-4',
    title: 'Онлайн-лекция: Грузия в средние века',
    description:
      'Цикл лекций «История Закавказья» продолжается. В этот раз — Грузия в период расцвета царства Тамары. Расскажем о политическом устройстве, культуре, архитектуре и отношениях с соседями.',
    type: 'lecture',
    location: null,
    address:  null,
    startsAt: new Date('2025-05-28T19:00:00'),
    endsAt:   new Date('2025-05-28T21:00:00'),
    coverUrl: null,
    isFree:   true,
    price:    null,
    currency: 'RUB',
    maxSeats: null,
    isOnline: true,
    onlineUrl: 'https://example.com/zoom',
    createdAt: new Date('2025-04-08'),
  },
  {
    id: 'evt-5',
    title: 'Экскурсия «Кавказские реликвии» в Эрмитаже',
    description:
      'Тематическая экскурсия по залам Эрмитажа, посвящённым культуре и искусству народов Кавказа. Оружие, ювелирные украшения, ковры и рукописи XI–XIX веков из постоянной коллекции музея.',
    type: 'tour',
    location: 'Государственный Эрмитаж',
    address:  'Санкт-Петербург, Дворцовая пл. 2',
    startsAt: new Date('2025-06-07T12:00:00'),
    endsAt:   new Date('2025-06-07T14:00:00'),
    coverUrl: null,
    isFree:   false,
    price:    800,
    currency: 'RUB',
    maxSeats: 20,
    isOnline: false,
    onlineUrl: null,
    createdAt: new Date('2025-04-12'),
  },
  {
    id: 'evt-6',
    title: 'Читательский клуб: «Герой нашего времени»',
    description:
      'Совместное чтение и обсуждение романа Лермонтова в контексте эпохи и реального Кавказа. Поговорим о прообразах героев, точности описаний природы и быта горцев, значении романа для изучения региона.',
    type: 'meeting',
    location: 'Кофейня «Аул»',
    address:  'Москва, Пятницкая ул. 27',
    startsAt: new Date('2025-06-12T19:30:00'),
    endsAt:   new Date('2025-06-12T21:30:00'),
    coverUrl: null,
    isFree:   true,
    price:    null,
    currency: 'RUB',
    maxSeats: 25,
    isOnline: false,
    onlineUrl: null,
    createdAt: new Date('2025-04-15'),
  },
]
